"""Configuration management for MegaMind."""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Project root
PROJECT_ROOT = Path(__file__).parent.resolve()

# API Keys
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
XAI_API_KEY = os.getenv("XAI_API_KEY", "")

# Models
CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-6")
GROK_MODEL = os.getenv("GROK_MODEL", "grok-3-latest")

# Storage paths
EXTRACTIONS_PATH = Path(os.getenv("EXTRACTIONS_PATH", PROJECT_ROOT / "extractions")).resolve()
OBSIDIAN_VAULT_PATH = os.getenv("OBSIDIAN_VAULT_PATH", "")
INDEX_FILE = EXTRACTIONS_PATH / "INDEX.md"

# Grok API (xAI uses OpenAI-compatible endpoint)
GROK_API_BASE = "https://api.x.ai/v1"

# CI mode — detected automatically in GitHub Actions, or set CI=true
CI_MODE = os.getenv("CI", "").lower() in ("true", "1") or os.getenv("GITHUB_ACTIONS", "") == "true"

# User-Agent for web scraping
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

# === Discord (MegaMind bot) ===
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN", "")
DISCORD_SERVER_ID = int(os.getenv("DISCORD_SERVER_ID", "0"))
DISCORD_EXTRACT_CHANNEL_ID = int(os.getenv("DISCORD_EXTRACT_CHANNEL_ID", "0"))
DISCORD_OUTPUT_CHANNEL_ID = int(os.getenv("DISCORD_OUTPUT_CHANNEL_ID", "0"))

# === YouTube Playlist Watcher ===
YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")
YOUTUBE_EXTRACT_PLAYLIST_ID = os.getenv("YOUTUBE_EXTRACT_PLAYLIST_ID", "")
YOUTUBE_COMPLETED_PLAYLIST_ID = os.getenv("YOUTUBE_COMPLETED_PLAYLIST_ID", "")
YOUTUBE_POLL_INTERVAL = int(os.getenv("YOUTUBE_POLL_INTERVAL", "3600"))  # seconds, default 1 hour
YOUTUBE_FAILED_RETRY_COOLDOWN = int(os.getenv("YOUTUBE_FAILED_RETRY_COOLDOWN", "21600"))

# YouTube OAuth2 — generated by  python youtube_auth.py
YOUTUBE_CLIENT_SECRET_FILE = PROJECT_ROOT / "client_secret.json"
YOUTUBE_TOKEN_FILE = PROJECT_ROOT / "youtube_token.json"

# === Legacy GitHub issue queue ===
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "onekiller89/MegaMind")

# === Controlled Discord work intake ===
DISCORD_WORK_INTAKE_ENABLED = os.getenv("DISCORD_WORK_INTAKE_ENABLED", "false").lower() in ("true", "1", "yes")
DISCORD_WORK_INTAKE_REACTOR_IDS = {
    int(value) for value in os.getenv("DISCORD_WORK_INTAKE_REACTOR_IDS", "").split(",") if value.strip()
}
WORK_INTAKE_ALLOWED_EXECUTORS = {
    value.strip() for value in os.getenv("WORK_INTAKE_ALLOWED_EXECUTORS", "").split(",") if value.strip()
}
WORK_INTAKE_ALLOWED_TARGETS = {
    value.strip() for value in os.getenv("WORK_INTAKE_ALLOWED_TARGETS", "").split(",") if value.strip()
}
WORK_INTAKE_RECORDS_PATH = Path(
    os.getenv("WORK_INTAKE_RECORDS_PATH", PROJECT_ROOT / "data" / "work-intakes.json")
).resolve()
WORK_INTAKE_AUDIT_PATH = Path(
    os.getenv("WORK_INTAKE_AUDIT_PATH", PROJECT_ROOT / "data" / "work-intake-audit.jsonl")
).resolve()
